language: java
jdk: oraclejdk11
dist: trusty

script: mvn -B verify -P bower -DskipFrontend -Dcom.vaadin.testbench.Parameters.testsInParallel=2 -Dvaadin.proKey=$VAADIN_PRO_KEY -Dsauce.user=$SAUCE_USER -Dsauce.sauceAccessKey=$SAUCE_ACCESSKEY

# Cache requires a master build
branches:
  only:
    - main

cache:
  directories:
    - $HOME/.m2

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/vaadin-crud-flow
